Foi criado um arquivo chamado limpeza_base_varejo.ipynb a partir do original para não alterar o arquivo original, onde será realizado a limpeza e tratamento dos dados, removendo valores nulos, duplicados e inconsistentes, além de padronizar os formatos das colunas para facilitar a análise posterior.

Depois de realizar a criação do ambiente vistual e installar as bibliotecas pandas, numpy, matplotlib e seaborn, será importado o arquivo de dados "dados_varejo.csv" para análise e tratamento.

Sera importados as bibliotecas pandas para manipulação de dados, numpy para operações matemáticas, matplotlib e seaborn para visualização de dados. Em seguida, será carregado o arquivo CSV em um DataFrame do pandas para iniciar o processo de limpeza e tratamento dos dados.

Descrição das tabelas:

1. DATA: Data da compra;
2. CO_ID: Identificação do número de compra (número da nota fiscal);
3. CL_ID: Identificação do cliente (número do cliente);
4. CL_GENERO: Sexo biológico informado pelo cliente;
2
5. CL_EC: Estado civil do cliente:
1: Casado ou união estával;
2: Divorciado;
3: Separado;
4. Solteiro;
5: Viúvo.
6. CL_FHL: Número de filhos do cliente;
7. CL_SEG: Segmentação econômica do cliente (classe A, B ou C);
8. PR_ID: Código do produto (SKU) adquirido;
9. PR_CAT: Categoria do produto adquirido;
10. PR_NOME: Nome do produto adquirido.

Importando as bibliotecas necessárias para a análise e tratamento dos dados:

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import re
import datetime

In [ ]:
#Carregando o arquivo CSV em um DataFrame do pandas para iniciar o processo de limpeza e tratamento dos dados.
df = pd.read_csv("Base Varejo.csv")
df.head()

  DATA;CO_ID;CL_ID;CL_GENERO;CL_EC;CL_FHL;CL_SEG;PR_ID;PR_CAT;PR_NOME;;;;
0  01/02/2019;1000;534;M;4;1;C;67;BEBIDAS;REFRIGE...
1  01/02/2019;1000;534;M;4;1;C;70;BEBIDAS;REFRIGE...
2  01/02/2019;1000;534;M;4;1;C;178;HIGIENE;LENCO ...
3  01/02/2019;1000;534;M;4;1;C;4;ALIMENTOS;ABACAX...
4  01/02/2019;1000;534;M;4;1;C;175;LIMPEZA;LIMPAD...

In [19]:
print(df.head())

  DATA;CO_ID;CL_ID;CL_GENERO;CL_EC;CL_FHL;CL_SEG;PR_ID;PR_CAT;PR_NOME;;;;
0  01/02/2019;1000;534;M;4;1;C;67;BEBIDAS;REFRIGE...
1  01/02/2019;1000;534;M;4;1;C;70;BEBIDAS;REFRIGE...
2  01/02/2019;1000;534;M;4;1;C;178;HIGIENE;LENCO ...
3  01/02/2019;1000;534;M;4;1;C;4;ALIMENTOS;ABACAX...
4  01/02/2019;1000;534;M;4;1;C;175;LIMPEZA;LIMPAD...

Observe que o df mostrado não é possivel visualizar de forma entendivel por isso seram escolhidas apenas as colunas mais importantes para a análise e tratamento dos dados, que são: 'DATA', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'PR_CAT', 'PR_NOME'

In [ ]:
df_enxuto= pd.read_csv('Base Varejo.csv', sep=";", encoding='latin-1', index_col='CO_ID' ,usecols=['CL_ID','DATA','CL_GENERO', 'CL_EC', 'CL_FHL', 'PR_CAT', 'PR_NOME'], nrows=100)

df_enxuto.head()

,DATA,CL_ID,CL_GENERO,CL_EC,CL_FHL,PR_CAT,PR_NOME
CO_ID,,,,,,,
1000,01/02/2019,534,M,4,1,BEBIDAS,REFRIGERANTE GUARANA
1000,01/02/2019,534,M,4,1,BEBIDAS,REFRIGERANTE OUTROS
1000,01/02/2019,534,M,4,1,HIGIENE,LENCO UMEDECIDO
1000,01/02/2019,534,M,4,1,ALIMENTOS,ABACAXI
1000,01/02/2019,534,M,4,1,LIMPEZA,LIMPADOR MULTIUSO

In [37]:
df_enxuto.info()

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 7 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   DATA       830000 non-null  str
 1   CL_ID      830000 non-null  int64
 2   CL_GENERO  830000 non-null  str
 3   CL_EC      830000 non-null  int64
 4   CL_FHL     830000 non-null  int64
 5   PR_CAT     830000 non-null  str
 6   PR_NOME    830000 non-null  str
dtypes: int64(3), str(4)
memory usage: 44.3 MB